name: NMR_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - gh
  - jupyterlab
  - openssl
  - pip
  - pydantic
  - rdkit
  - scikit-learn
  - seaborn
  - tensorboard
  - pytorch::pytorch-cuda=12.1
  - pip:
      - antlr4-python3-runtime==4.9.3
      - h5py==3.12.1
      - hydra-core==1.3.2
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - omegaconf==2.3.0
      - pytorch-lightning==2.4.0
      - torchmetrics==1.6.0
      - standard-imghdr==3.13.0
